name: Keep Repository Alive

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1号 UTC 0点执行（北京时间早上8点）
  workflow_dispatch:  # 支持手动触发

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update keepalive file
        run: |
          echo "Keep alive update at $(date)" >> keepalive.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add keepalive.txt
          git commit -m "keep alive update"
          git push
